import { Emojies } from "../types/app.types";

export const symbolEmoticonArray: Emojies[] = [
  //    currency
  {
    label: "USD",
    type: "Currency",
    emoji: "$",
    keywords: ["dollar", "usd", "money", "cash", "finance"],
  },
  {
    label: "Euro",
    type: "Currency",
    emoji: "€",
    keywords: ["euro", "eur", "europe", "money", "cash"],
  },
  {
    label: "British Pound",
    type: "Currency",
    emoji: "£",
    keywords: ["pound", "gbp", "sterling", "money", "uk"],
  },
  {
    label: "Yen / Yuan",
    type: "Currency",
    emoji: "¥",
    keywords: ["yen", "yuan", "jpy", "cny", "japan", "china"],
  },
  {
    label: "INR",
    type: "Currency",
    emoji: "₹",
    keywords: ["rupee", "inr", "india", "money"],
  },
  {
    label: "Russian Ruble",
    type: "Currency",
    emoji: "₽",
    keywords: ["ruble", "rub", "russia", "money"],
  },
  {
    label: "South Korean Won",
    type: "Currency",
    emoji: "₩",
    keywords: ["won", "krw", "korea", "money"],
  },
  {
    label: "Thai Baht",
    type: "Currency",
    emoji: "฿",
    keywords: ["baht", "thb", "thailand", "money"],
  },
  {
    label: "Turkish Lira",
    type: "Currency",
    emoji: "₺",
    keywords: ["lira", "try", "turkey", "money"],
  },
  {
    label: "Swiss Franc",
    type: "Currency",
    emoji: "₣",
    keywords: ["franc", "chf", "switzerland", "money", "cash"],
  },
  {
    label: "Israeli Shekel",
    type: "Currency",
    emoji: "₪",
    keywords: ["shekel", "ils", "israel", "money"],
  },
  {
    label: "VN Dong",
    type: "Currency",
    emoji: "₫",
    keywords: ["dong", "vnd", "vietnam", "money"],
  },
  {
    label: "Hryvnia",
    type: "Currency",
    emoji: "₴",
    keywords: ["hryvnia", "uah", "ukraine", "money"],
  },
  {
    label: "Peso",
    type: "Currency",
    emoji: "₱",
    keywords: ["peso", "php", "philippines", "money"],
  },
  {
    label: "Cedi",
    type: "Currency",
    emoji: "₵",
    keywords: ["cedi", "ghs", "ghana", "money"],
  },
  {
    label: "Tugrik",
    type: "Currency",
    emoji: "₮",
    keywords: ["tugrik", "mnt", "mongolia", "money"],
  },
  {
    label: "Lao Kip",
    type: "Currency",
    emoji: "₭",
    keywords: ["kip", "lak", "laos", "money"],
  },
  {
    label: "Sucre",
    type: "Currency",
    emoji: "₳",
    keywords: ["sucre", "ecuador", "historic", "money"],
  },
  {
    label: "cash",
    type: "Currency",
    emoji: "¤",
    keywords: ["generic", "currency", "cash", "money"],
  },
  // --- Arithmetic / Math ---
  {
    label: "Plus",
    type: "Arithmetic",
    emoji: "+",
    keywords: ["add", "plus", "sum", "increase", "positive"],
  },
  {
    label: "Minus",
    type: "Arithmetic",
    emoji: "-",
    keywords: ["subtract", "minus", "difference", "decrease", "negative"],
  },
  {
    label: "Times",
    type: "Arithmetic",
    emoji: "×", // Unicode 'Multiplication Sign'
    keywords: ["multiply", "times", "product", "cross"],
  },
  {
    label: "Divide",
    type: "Arithmetic",
    emoji: "÷", // Unicode 'Division Sign'
    keywords: ["divide", "quotient", "ratio"],
  },
  {
    label: "Equals",
    type: "Arithmetic",
    emoji: "=",
    keywords: ["equal", "result", "is", "equality"],
  },
  {
    label: "Not Equal",
    type: "Arithmetic",
    emoji: "≠",
    keywords: ["not equal", "unequal", "difference"],
  },
  {
    label: "Approx",
    type: "Arithmetic",
    emoji: "≈",
    keywords: ["approximate", "almost equal", "estimate"],
  },
  {
    label: "Less Than",
    type: "Arithmetic",
    emoji: "<",
    keywords: ["smaller", "less", "lower"],
  },
  {
    label: "Greater Than",
    type: "Arithmetic",
    emoji: ">",
    keywords: ["bigger", "greater", "higher"],
  },
  {
    label: "Equal To",
    type: "Arithmetic",
    emoji: "≤",
    keywords: ["less equal", "at most"],
  },
  {
    label: "Greater Equal",
    type: "Arithmetic",
    emoji: "≥",
    keywords: ["greater equal", "at least"],
  },
  {
    label: "Percent",
    type: "Arithmetic",
    emoji: "%",
    keywords: ["percentage", "rate", "ratio", "out of 100"],
  },
  {
    label: "Permille",
    type: "Arithmetic",
    emoji: "‰",
    keywords: ["per thousand", "basis points", "rate"],
  },
  {
    label: "Infinity",
    type: "Arithmetic",
    emoji: "∞",
    keywords: ["endless", "limitless", "math", "forever"],
  },
  {
    label: "Square Root",
    type: "Arithmetic",
    emoji: "√",
    keywords: ["root", "radical", "math"],
  },
  {
    label: "Power",
    type: "Arithmetic",
    emoji: "^",
    keywords: ["caret", "power", "exponent", "to the power of"],
  },
  {
    label: "Pi",
    type: "Arithmetic",
    emoji: "π",
    keywords: ["pi", "constant", "geometry", "circle", "3.14"],
  },
  {
    label: "Sigma",
    type: "Arithmetic",
    emoji: "Σ",
    keywords: ["sigma", "sum", "total", "series", "math"],
  },
  {
    label: "Integral",
    type: "Arithmetic",
    emoji: "∫",
    keywords: ["calculus", "integration", "area", "math"],
  },
  {
    label: "Partial",
    type: "Arithmetic",
    emoji: "∂",
    keywords: ["derivative", "calculus", "partial"],
  },
  {
    label: "Delta",
    type: "Arithmetic",
    emoji: "Δ",
    keywords: ["delta", "change", "difference", "triangle"],
  },
  {
    label: "varies as",
    type: "Arithmetic",
    emoji: "∝",
    keywords: ["proportional", "varies as", "relation"],
  },
  {
    label: "proof",
    type: "Arithmetic",
    emoji: "∴",
    keywords: ["therefore", "conclusion", "logic", "proof"],
  },
  {
    label: "Since",
    type: "Arithmetic",
    emoji: "∵",
    keywords: ["because", "since", "reason", "logic"],
  },
  {
    label: "Diameter",
    type: "Arithmetic",
    emoji: "∅",
    keywords: ["empty set", "null", "diameter", "math"],
  },
  {
    label: "element of",
    type: "Arithmetic",
    emoji: "∈",
    keywords: ["element of", "belongs to", "set theory"],
  },
  {
    label: "Angle",
    type: "Arithmetic",
    emoji: "∠",
    keywords: ["angle", "geometry", "corner"],
  },
  {
    label: "right angle",
    type: "Arithmetic",
    emoji: "⊥",
    keywords: ["perpendicular", "orthogonal", "right angle"],
  },
  {
    label: "Fn",
    type: "Arithmetic",
    emoji: "ƒ",
    keywords: ["function", "math", "mapping"],
  },
  // quaso
  { label: "happy", type: "Quaso", emoji: "(＾▽＾)", keywords: ["happy", "smile", "joy"] },
  { label: "joy and playful", type: "Quaso", emoji: "(≧◡≦)", keywords: ["joy", "playful", "cute"] },
  { label: "love", type: "Quaso", emoji: "(♡˙︶˙♡)", keywords: ["love", "heart", "cute"] },
  { label: "kiss", type: "Quaso", emoji: "( ˘ ³˘)♥", keywords: ["kiss", "love", "affection"] },
  { label: "sad", type: "Quaso", emoji: "(；︵；)", keywords: ["sad", "cry", "upset"] },
  { label: "crying", type: "Quaso", emoji: "(T_T)", keywords: ["crying", "tears", "sad"] },
  { label: "depressed", type: "Quaso", emoji: "(︶︹︶)", keywords: ["depressed", "down", "sad"] },
  { label: "angry", type: "Quaso", emoji: "(╬ಠ益ಠ)", keywords: ["angry", "mad", "rage"] },
  { label: "annoyed", type: "Quaso", emoji: "(¬_¬)", keywords: ["annoyed", "unimpressed", "meh"] },
  {
    label: "confused",
    type: "Quaso",
    emoji: "(・_・ヾ",
    keywords: ["confused", "thinking", "unsure"],
  },
  {
    label: "thinking",
    type: "Quaso",
    emoji: "(￢_￢)",
    keywords: ["thinking", "suspicious", "hmm"],
  },
  { label: "surprised", type: "Quaso", emoji: "(⊙_⊙)", keywords: ["surprised", "shocked", "wow"] },
  { label: "shrug", type: "Quaso", emoji: "¯\\_(ツ)_/¯", keywords: ["shrug", "idk", "whatever"] },
  {
    label: "table flip",
    type: "Quaso",
    emoji: "(╯°□°）╯︵ ┻━┻",
    keywords: ["table flip", "angry", "rage"],
  },
  { label: "dead", type: "Quaso", emoji: "(x_x)", keywords: ["dead", "knocked out", "fail"] },
  { label: "cute bear", type: "Quaso", emoji: "ʕ•ᴥ•ʔ", keywords: ["bear", "cute", "animal"] },
  { label: "cute cat", type: "Quaso", emoji: "(=^･ω･^=)", keywords: ["cat", "cute", "animal"] },
  {
    label: "victory",
    type: "Quaso",
    emoji: "(ง •̀_•́)ง",
    keywords: ["fight", "victory", "determined"],
  },
  { label: "strong", type: "Quaso", emoji: "ᕙ(⇀‸↼‶)ᕗ", keywords: ["strong", "muscle", "power"] },
  {
    label: "Table Flip",
    type: "Quaso",
    emoji: "(╯°□°）╯︵ ┻━┻",
    keywords: ["table flip", "rage", "frustration", "anger"],
  },
  {
    label: "blushing",
    type: "Quaso",
    emoji: "(⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄)",
    keywords: ["blush", "shy", "embarrassed"],
  },
  { label: "winking", type: "Quaso", emoji: "(^.~)", keywords: ["wink", "flirt", "playful"] },
  { label: "sleeping", type: "Quaso", emoji: "(－_－) zzZ", keywords: ["sleep", "tired", "rest"] },
  { label: "dance", type: "Quaso", emoji: "└(＾＾)┐", keywords: ["dance", "music", "happy"] },
  { label: "excited", type: "Quaso", emoji: "o(>ω<)o", keywords: ["excited", "happy", "yay"] },
  { label: "scared", type: "Quaso", emoji: "(ノдヽ)", keywords: ["scared", "hide", "fear"] },
  { label: "pouting", type: "Quaso", emoji: " ( ￣＾￣)", keywords: ["pout", "grumpy", "mad"] },
  {
    label: "star eyes",
    type: "Quaso",
    emoji: "(☆▽☆)",
    keywords: ["stars", "amazing", "impressed"],
  },
  { label: "hug", type: "Quaso", emoji: "(づ◡﹏◡)づ", keywords: ["hug", "cuddle", "comfort"] },
  {
    label: "lenny face",
    type: "Quaso",
    emoji: "( ͡° ͜ʖ ͡°)",
    keywords: ["lenny", "smirk", "suspicious"],
  },
  { label: "dog", type: "Quaso", emoji: "V●ᴥ●V", keywords: ["dog", "puppy", "animal"] },
  {
    label: "sparkle happy",
    type: "Quaso",
    emoji: " (✧∀✧)/",
    keywords: ["sparkle", "happy", "fabulous"],
  },
  { label: "worried", type: "Quaso", emoji: "(ーー;)", keywords: ["worried", "nervous", "sweat"] },
  { label: "no thanks", type: "Quaso", emoji: "(￣ω￣)ゞ", keywords: ["salute", "ok", "bye"] },
  {
    label: "cool",
    type: "Quaso",
    emoji: "(⌐■_■)",
    keywords: ["cool", "sunglasses", "deal with it"],
  },
  {
    label: "money eyes",
    type: "Quaso",
    emoji: " [̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]",
    keywords: ["money", "rich", "cash"],
  },
  {
    label: "speechless",
    type: "Quaso",
    emoji: "(O_O;)",
    keywords: ["speechless", "wow", "awkward"],
  },
  { label: "flexing", type: "Quaso", emoji: "ᕦ(ò_ó)ᕤ", keywords: ["strong", "flex", "tough"] },
  {
    label: "magical",
    type: "Quaso",
    emoji: "╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ",
    keywords: ["magic", "wizard", "sparkle"],
  },
  { label: "running", type: "Quaso", emoji: "ε=ε=┌(;￣▽￣)┘", keywords: ["run", "fast", "hurry"] },
  // --- Happy/Positive ---
  {
    label: "Basic Smile",
    type: "Sy happy & sad",
    emoji: ":)",
    keywords: [":-)", "happy", "smile", "joy"],
  },
  {
    label: "Big Grin",
    type: "Sy happy & sad",
    emoji: ":D",
    keywords: [":-D", "=D", "laugh", "big smile"],
  },
  {
    label: "Wink",
    type: "Sy happy & sad",
    emoji: ";)",
    keywords: [";-)", "wink", "flirt", "sarcasm"],
  },
  {
    label: "Tongue",
    type: "Sy happy & sad",
    emoji: ":P",
    keywords: [":-P", ":p", ":-p", "tongue", "silly", "playful"],
  },
  {
    label: "Kiss",
    type: "Sy happy & sad",
    emoji: ":*",
    keywords: [":-*", ":x", "kiss", "smooch", "love"],
  },
  {
    label: "Heart",
    type: "Sy happy & sad",
    emoji: "<3",
    keywords: ["heart", "love", "less than three"],
  },

  // --- Neutral/Skeptical ---
  {
    label: "unsure",
    type: "Sy happy & sad",
    emoji: ":/",
    keywords: [":-/", ":\\", ":-\\", "skeptical", "unsure", "annoyed", "uneasy"],
  },
  {
    label: "Neutral",
    type: "Sy happy & sad",
    emoji: ":|",
    keywords: [":-|", "straight face", "indifferent", "no expression"],
  },
  {
    label: "Shock",
    type: "Sy happy & sad",
    emoji: ":O",
    keywords: [":-O", ":o", "shock", "surprise", "yell"],
  },

  // --- Negative/Sad ---
  {
    label: "Frown",
    type: "Sy happy & sad",
    emoji: ":(",
    keywords: [":-(", "=(", "sad", "frown", "unhappy"],
  },
  {
    label: "Crying",
    type: "Sy happy & sad",
    emoji: ":'(",
    keywords: [":'-(", "cry", "tear", "sobbing"],
  },
  {
    label: "Angry",
    type: "Sy happy & sad",
    emoji: ">:(",
    keywords: [">:-(", "mad", "angry", "furious"],
  },
];

export const graphicEmojiArray: Emojies[] = [
  // --- Faces ---
  {
    label: "Grin",
    type: "Faces",
    emoji: "😀",
    keywords: ["happy", "smile", "joy", "grin", "face"],
  },
  {
    label: "Smile",
    type: "Faces",
    emoji: "😊",
    keywords: ["bliss", "pleased", "happy", "cute", "smiling eyes"],
  },
  {
    label: "joy",
    type: "Faces",
    emoji: "😂",
    keywords: ["laughing", "crying", "joy", "lol", "funny"],
  },
  {
    label: "Wink",
    type: "Faces",
    emoji: "😉",
    keywords: ["playful", "flirtatious", "sarcasm", "wink"],
  },
  {
    label: ":3",
    type: "Faces",
    emoji: "😗",
    keywords: ["kiss", "smooch", "love", "pucker"],
  },
  {
    label: "love",
    type: "Faces",
    emoji: "😍",
    keywords: ["love", "heart", "eyes", "adoration", "excited"],
  },
  {
    label: "face hearts",
    type: "Faces",
    emoji: "🥰",
    keywords: ["love", "hearts", "caring", "excited", "in_love"],
  },
  {
    label: "kiss",
    type: "Faces",
    emoji: "😘",
    keywords: ["kiss", "love", "blowing", "affection", "gratitude"],
  },
  {
    label: "Think",
    type: "Faces",
    emoji: "🤔",
    keywords: ["thinking", "pondering", "doubt", "consideration"],
  },
  {
    label: "Rolling Eyes",
    type: "Faces",
    emoji: "🙄",
    keywords: ["annoyance", "disdain", "sarcasm", "boredom", "eye roll"],
  },
  {
    label: "Neutral",
    type: "Faces",
    emoji: "😐",
    keywords: ["indifferent", "straight face", "unimpressed", "neutral"],
  },
  {
    label: "blank face",
    type: "Faces",
    emoji: "😑",
    keywords: ["blank", "flat", "apathetic", "no expression"],
  },
  {
    label: "sad",
    type: "Faces",
    emoji: "😞",
    keywords: ["sad", "unhappy", "dejected", "disappointment"],
  },
  {
    label: "tear",
    type: "Faces",
    emoji: "😢",
    keywords: ["sad", "tear", "unhappy", "crying", "sob"],
  },
  {
    label: "angry",
    type: "Faces",
    emoji: "😡",
    keywords: ["angry", "mad", "furious", "pout", "rage"],
  },
  {
    label: "STFU",
    type: "Faces",
    emoji: "🤬",
    keywords: ["angry", "mad", "furious", "curse", "rage", "bait"],
  },
  {
    label: "shock",
    type: "Faces",
    emoji: "😲",
    keywords: ["shock", "surprise", "amazement", "gasp"],
  },
  {
    label: "Zipped Mouth",
    type: "Faces",
    emoji: "🤐",
    keywords: ["silent", "secret", "mute", "no comment"],
  },
  {
    label: "Sleep",
    type: "Faces",
    emoji: "😴",
    keywords: ["sleep", "tired", "zzz", "bedtime"],
  },
  {
    label: "joyful",
    type: "Faces",
    emoji: "😁",
    keywords: ["joyful", "beaming", "happy", "big grin"],
  },
  {
    label: "Sweat",
    type: "Faces",
    emoji: "😅",
    keywords: ["relief", "nervous", "awkward", "sweat", "phew"],
  },
  {
    label: "Halo",
    type: "Faces",
    emoji: "😇",
    keywords: ["angel", "innocent", "pure", "good", "halo"],
  },
  {
    label: "down",
    type: "Faces",
    emoji: "😔",
    keywords: ["sad", "thoughtful", "pensive", "melancholy", "down"],
  },
  {
    label: "Confused",
    type: "Faces",
    emoji: "😕",
    keywords: ["confused", "puzzled", "uncertain", "huh"],
  },
  {
    label: "Weary",
    type: "Faces",
    emoji: "😩",
    keywords: ["tired", "weary", "frustrated", "distressed", "ugh"],
  },
  {
    label: "pain",
    type: "Faces",
    emoji: "😫",
    keywords: ["struggle", "pain", "determined", "perseverance"],
  },
  {
    label: "Fear",
    type: "Faces",
    emoji: "😱",
    keywords: ["horror", "fear", "scared", "shock", "scream"],
  },
  {
    label: "Hushed",
    type: "Faces",
    emoji: "🤫",
    keywords: ["quiet", "shocked", "surprised", "hush", "whisper"],
  },
  {
    label: "Hot",
    type: "Faces",
    emoji: "🥵",
    keywords: ["hot", "sweaty", "heatwave", "fever", "overheated"],
  },
  {
    label: "Cold",
    type: "Faces",
    emoji: "🥶",
    keywords: ["cold", "freezing", "ice", "shivering"],
  },
  {
    label: "Woozy",
    type: "Faces",
    emoji: "🥴",
    keywords: ["dizzy", "drunk", "woozy", "sick", "disoriented"],
  },
  {
    label: "oops",
    type: "Faces",
    emoji: "🤭",
    keywords: ["giggle", "oops", "surprise", "chuckle", "covering mouth"],
  },
  {
    label: "cowboy",
    type: "Faces",
    emoji: "🤠",
    keywords: ["cowboy", "western", "yeehaw", "rodeo"],
  },
  {
    label: "wink playful",
    type: "Faces",
    emoji: "😜",
    keywords: ["happy", "playful", "positive", "fun", "wink playful"],
  },
  {
    label: "playful",
    type: "Faces",
    emoji: "😝",
    keywords: ["happy", "playful", "positive", "fun"],
  },
  {
    label: "goon",
    type: "Faces",
    emoji: "😛",
    keywords: ["happy", "playful", "positive", "fun", "Tongue", "goon"],
  },
  {
    label: "rich",
    type: "Faces",
    emoji: "🤑",
    keywords: ["happy", "playful", "positive", "money", "Tongue", "rich"],
  },
  {
    label: "Silly",
    type: "Faces",
    emoji: "🤪",
    keywords: ["happy", "playful", "positive", "Silly", "Tongue"],
  },
  {
    label: "amazed",
    type: "Faces",
    emoji: "🤩",
    keywords: ["amazed", "celebration", "impressed", "fun", "wonderful"],
  },
  {
    label: "party",
    type: "Faces",
    emoji: "🥳",
    keywords: ["party", "celebration", "birthday", "fun"],
  },
  {
    label: "party",
    type: "Faces",
    emoji: "🤨",
    keywords: ["skepticism", "confusion", "disbelief", "Really", "hmm"],
  },
  {
    label: "judge",
    type: "Faces",
    emoji: "🧐",
    keywords: ["skepticism", "confusion", "disbelief", "deep thought", "curiosity"],
  },
  {
    label: "Nerd",
    type: "Faces",
    emoji: "🤓",
    keywords: ["Nerd", "smart", "learning", "geek"],
  },
  {
    label: "Cool",
    type: "Faces",
    emoji: "😎",
    keywords: ["party", "celebration", "cool", "fun"],
  },
  {
    label: "Unc",
    type: "Faces",
    emoji: "🥸",
    keywords: ["disguise", "mischievous", "funny", "fun", "unc"],
  },
  {
    label: "cat smile",
    type: "Faces",
    emoji: "😸",
    keywords: ["cat", "happy", "grinning", "eyes"],
  },
  {
    label: "cat joy",
    type: "Faces",
    emoji: "😹",
    keywords: ["cat", "tears", "joy", "laugh", "crying"],
  },
  {
    label: "cat",
    type: "Faces",
    emoji: "😻",
    keywords: ["cat", "love", "heart", "adoration", "crush"],
  },
  {
    label: "cat wry",
    type: "Faces",
    emoji: "😼",
    keywords: ["cat", "smirk", "wry", "cynical", "sarcasm"],
  },
  {
    label: "kissing cat",
    type: "Faces",
    emoji: "😽",
    keywords: ["cat", "kiss", "muah", "affection", "smooch"],
  },
  {
    label: "pouting cat",
    type: "Faces",
    emoji: "😾",
    keywords: ["cat", "pout", "angry", "grumpy", "mad"],
  },
  {
    label: "crying cat",
    type: "Faces",
    emoji: "😿",
    keywords: ["cat", "sad", "cry", "tear", "unhappy"],
  },
  {
    label: "weary cat",
    type: "Faces",
    emoji: "🙀",
    keywords: ["cat", "tired", "scared", "shocked", "yawning"],
  },
  // hands
  {
    label: "thumb up",
    type: "Gestures",
    emoji: "👍",
    keywords: ["thumb", "up", "like", "agree", "yes", "good"],
  },
  {
    label: "thumb down",
    type: "Gestures",
    emoji: "👎",
    keywords: ["thumb", "down", "dislike", "disagree", "no", "bad"],
  },
  {
    label: "ok",
    type: "Gestures",
    emoji: "👌",
    keywords: ["ok", "perfect", "good", "zero", "circle"],
  },
  {
    label: "victory",
    type: "Gestures",
    emoji: "✌️",
    keywords: ["peace", "victory", "two", "fingers", "v"],
  },
  {
    label: "finger heart",
    type: "Gestures",
    emoji: "🫰",
    keywords: ["love", "affection", "cute", "heart", "korean heart", "gesture"],
  },
  {
    label: "support and care",
    type: "Gestures",
    emoji: "🫶",
    keywords: ["love", "care", "support", "gratitude", "heart hands", "affection"],
  },
  {
    label: "offering",
    type: "Gestures",
    emoji: "🫴",
    keywords: ["give", "offer", "help", "present", "hand", "gesture"],
  },
  {
    label: "hand wave",
    type: "Gestures",
    emoji: "👋",
    keywords: ["wave", "hello", "goodbye", "hand"],
  },
  {
    label: "call me",
    type: "Gestures",
    emoji: "🤙",
    keywords: ["call", "me", "shaka", "hang_loose", "surf"],
  },
  {
    label: "clap",
    type: "Gestures",
    emoji: "👏",
    keywords: ["clap", "applause", "bravo", "congratulations"],
  },
  {
    label: "raised hands",
    type: "Gestures",
    emoji: "🙌",
    keywords: ["raise", "hands", "celebrate", "hooray", "praise"],
  },
  {
    label: "fist bump",
    type: "Gestures",
    emoji: "👊",
    keywords: ["fist", "punch", "bump", "hello", "violence"],
  },
  {
    label: "fist",
    type: "Gestures",
    emoji: "🤛",
    keywords: ["fist", "left", "punch", "hand", "oncoming"],
  },
  {
    label: "index",
    type: "Gestures",
    emoji: "👉",
    keywords: ["finger", "point", "right", "direction", "index"],
  },
  {
    label: "pointing",
    type: "Gestures",
    emoji: "👆",
    keywords: ["finger", "point", "up", "direction", "index"],
  },
  {
    label: "vulcan",
    type: "Gestures",
    emoji: "🖖",
    keywords: ["vulcan", "spock", "live", "prosper", "star_trek"],
  },
  {
    label: "crossed fingers",
    type: "Gestures",
    emoji: "🤞",
    keywords: ["fingers", "crossed", "luck", "hope", "wish"],
  },
  {
    label: "open hands",
    type: "Gestures",
    emoji: "👐",
    keywords: ["open", "hands", "hug", "give", "receive", "caring"],
  },
  {
    label: "folded hands",
    type: "Gestures",
    emoji: "🙏",
    keywords: ["pray", "hands", "thanks", "please", "namaste", "hope"],
  },
  {
    label: "hand shake",
    type: "Gestures",
    emoji: "🤝",
    keywords: ["shake", "handshake", "deal", "meeting", "agreement"],
  },
  {
    label: "pointing up",
    type: "Gestures",
    emoji: "☝️",
    keywords: ["index", "up", "point", "number_one", "attention"],
  },
  {
    label: "pointing left",
    type: "Gestures",
    emoji: "👈",
    keywords: ["finger", "point", "left", "direction", "index"],
  },
  {
    label: "pointing down",
    type: "Gestures",
    emoji: "👇",
    keywords: ["finger", "point", "down", "direction", "index"],
  },
  {
    label: "rockon",
    type: "Gestures",
    emoji: "🤘",
    keywords: ["rock", "horn", "metal", "sign", "devil", "music"],
  },
  {
    label: "Rocker",
    type: "Gestures",
    emoji: "🤟",
    keywords: ["i_love_you", "sign", "hand", "iloveyou"],
  },
  {
    label: "pinch",
    type: "Gestures",
    emoji: "🤏",
    keywords: ["pinch", "small", "little", "tiny", "amount"],
  },
  {
    label: "writing",
    type: "Gestures",
    emoji: "✍️",
    keywords: ["write", "hand", "pen", "note", "sign", "author"],
  },
  {
    label: "selfie",
    type: "Gestures",
    emoji: "🤳",
    keywords: ["selfie", "phone", "camera", "picture", "photo"],
  },

  // Positive or Negative
  {
    label: "100",
    type: "Positive or Negative",
    emoji: "💯",
    keywords: ["100", "perfect", "score", "top", "success", "excellent"],
  },
  {
    label: "popper",
    type: "Positive or Negative",
    emoji: "🎉",
    keywords: ["party", "celebration", "fun", "surprise", "congratulations"],
  },
  {
    label: "check",
    type: "Positive or Negative",
    emoji: "✅",
    keywords: ["check", "mark", "yes", "correct", "done", "complete"],
  },
  {
    label: "star",
    type: "Positive or Negative",
    emoji: "🌟",
    keywords: ["star", "shine", "quality", "magic", "night"],
  },
  {
    label: "sparkle",
    type: "Positive or Negative",
    emoji: "✨",
    keywords: ["sparkle", "glitter", "clean", "magic", "new"],
  },
  {
    label: "gift",
    type: "Positive or Negative",
    emoji: "🎁",
    keywords: ["gift", "present", "surprise", "birthday", "giving"],
  },
  {
    label: "trophy",
    type: "Positive or Negative",
    emoji: "🏆",
    keywords: ["trophy", "winner", "cup", "award", "achievement"],
  },
  {
    label: "money",
    type: "Positive or Negative",
    emoji: "💰",
    keywords: ["money", "cash", "wealth", "payment", "rich"],
  },
  {
    label: "red heart",
    type: "Positive or Negative",
    emoji: "❤️",
    keywords: ["love", "red", "romance", "affection", "heart"],
  },
  {
    label: "burning love",
    type: "Positive or Negative",
    emoji: "❤️‍🔥",
    keywords: ["passion", "intense love", "desire", "heart on fire", "romance"],
  },
  {
    label: "orange heart",
    type: "Positive or Negative",
    emoji: "🧡",
    keywords: ["love", "orange", "warmth", "caring", "heart"],
  },
  {
    label: "yellow heart",
    type: "Positive or Negative",
    emoji: "💛",
    keywords: ["love", "yellow", "friendship", "happiness", "heart"],
  },
  {
    label: "green heart",
    type: "Positive or Negative",
    emoji: "💚",
    keywords: ["love", "green", "nature", "health", "heart"],
  },
  {
    label: "blue heart",
    type: "Positive or Negative",
    emoji: "💙",
    keywords: ["love", "blue", "trust", "peace", "heart"],
  },
  {
    label: "purple heart",
    type: "Positive or Negative",
    emoji: "💜",
    keywords: ["love", "purple", "compassion", "sensitive", "heart"],
  },
  {
    label: "blackheart",
    type: "Positive or Negative",
    emoji: "🖤",
    keywords: ["love", "black", "sadness", "dark", "style", "heart"],
  },
  {
    label: "white heart",
    type: "Positive or Negative",
    emoji: "🤍",
    keywords: ["love", "white", "purity", "peace", "heart"],
  },

  //   negative
  {
    label: "cross",
    type: "Positive or Negative",
    emoji: "❌",
    keywords: ["cross", "mark", "no", "incorrect", "wrong", "delete"],
  },
  {
    label: "ban",
    type: "Positive or Negative",
    emoji: "🚫",
    keywords: ["no", "forbidden", "not_allowed", "block", "stop", "ban"],
  },
  {
    label: "stop",
    type: "Positive or Negative",
    emoji: "🛑",
    keywords: ["stop", "sign", "danger", "halt", "red"],
  },
  {
    label: "?",
    type: "Positive or Negative",
    emoji: "❓",
    keywords: ["question", "mark", "doubt", "confusion", "unknown"],
  },
  {
    label: "fire",
    type: "Positive or Negative",
    emoji: "🔥",
    keywords: ["fire", "flame", "hot", "danger", "burn", "trouble"],
  },
  {
    label: "skull",
    type: "Positive or Negative",
    emoji: "💀",
    keywords: ["skull", "death", "danger", "poison", "warning"],
  },
  {
    label: "bomb",
    type: "Positive or Negative",
    emoji: "💣",
    keywords: ["bomb", "explosion", "disaster", "warning", "attack"],
  },
  {
    label: "syringe",
    type: "Positive or Negative",
    emoji: "💉",
    keywords: ["syringe", "needle", "medicine", "illness", "hurt"],
  },

  //   animals & nature
  { label: "dog", type: "Animals & Nature", emoji: "🐶", keywords: ["dog", "pet", "animal"] },
  { label: "cat", type: "Animals & Nature", emoji: "🐱", keywords: ["cat", "pet", "animal"] },
  {
    label: "mouse",
    type: "Animals & Nature",
    emoji: "🐭",
    keywords: ["mouse", "rodent", "animal"],
  },
  {
    label: "hamster",
    type: "Animals & Nature",
    emoji: "🐹",
    keywords: ["hamster", "pet", "animal"],
  },
  {
    label: "rabbit",
    type: "Animals & Nature",
    emoji: "🐰",
    keywords: ["rabbit", "bunny", "animal"],
  },
  { label: "fox", type: "Animals & Nature", emoji: "🦊", keywords: ["fox", "wild", "animal"] },
  { label: "bear", type: "Animals & Nature", emoji: "🐻", keywords: ["bear", "wild", "animal"] },
  { label: "panda", type: "Animals & Nature", emoji: "🐼", keywords: ["panda", "bear", "animal"] },
  {
    label: "polar bear",
    type: "Animals & Nature",
    emoji: "🐻‍❄️",
    keywords: ["polar bear", "arctic", "animal"],
  },
  {
    label: "koala",
    type: "Animals & Nature",
    emoji: "🐨",
    keywords: ["koala", "marsupial", "animal"],
  },
  { label: "tiger", type: "Animals & Nature", emoji: "🐯", keywords: ["tiger", "wild", "animal"] },
  { label: "lion", type: "Animals & Nature", emoji: "🦁", keywords: ["lion", "wild", "animal"] },
  { label: "cow", type: "Animals & Nature", emoji: "🐮", keywords: ["cow", "farm", "animal"] },
  { label: "pig", type: "Animals & Nature", emoji: "🐷", keywords: ["pig", "farm", "animal"] },
  {
    label: "pig nose",
    type: "Animals & Nature",
    emoji: "🐽",
    keywords: ["pig", "snout", "animal"],
  },
  {
    label: "frog",
    type: "Animals & Nature",
    emoji: "🐸",
    keywords: ["frog", "amphibian", "animal"],
  },
  { label: "monkey face", type: "Animals & Nature", emoji: "🐵", keywords: ["monkey", "animal"] },
  {
    label: "see no evil",
    type: "Animals & Nature",
    emoji: "🙈",
    keywords: ["monkey", "see no evil"],
  },
  {
    label: "hear no evil",
    type: "Animals & Nature",
    emoji: "🙉",
    keywords: ["monkey", "hear no evil"],
  },
  {
    label: "speak no evil",
    type: "Animals & Nature",
    emoji: "🙊",
    keywords: ["monkey", "speak no evil"],
  },
  { label: "monkey", type: "Animals & Nature", emoji: "🐒", keywords: ["monkey", "animal"] },
  {
    label: "chicken",
    type: "Animals & Nature",
    emoji: "🐔",
    keywords: ["chicken", "bird", "animal"],
  },
  {
    label: "penguin",
    type: "Animals & Nature",
    emoji: "🐧",
    keywords: ["penguin", "bird", "animal"],
  },
  { label: "bird", type: "Animals & Nature", emoji: "🐦", keywords: ["bird", "animal"] },
  {
    label: "baby chick",
    type: "Animals & Nature",
    emoji: "🐤",
    keywords: ["chick", "bird", "animal"],
  },
  {
    label: "hatching chick",
    type: "Animals & Nature",
    emoji: "🐣",
    keywords: ["chick", "birth", "animal"],
  },
  {
    label: "front chick",
    type: "Animals & Nature",
    emoji: "🐥",
    keywords: ["chick", "bird", "animal"],
  },
  { label: "duck", type: "Animals & Nature", emoji: "🦆", keywords: ["duck", "bird", "animal"] },
  { label: "eagle", type: "Animals & Nature", emoji: "🦅", keywords: ["eagle", "bird", "animal"] },
  { label: "owl", type: "Animals & Nature", emoji: "🦉", keywords: ["owl", "bird", "animal"] },
  { label: "bat", type: "Animals & Nature", emoji: "🦇", keywords: ["bat", "night", "animal"] },
  { label: "wolf", type: "Animals & Nature", emoji: "🐺", keywords: ["wolf", "wild", "animal"] },
  { label: "boar", type: "Animals & Nature", emoji: "🐗", keywords: ["boar", "wild", "animal"] },
  { label: "horse", type: "Animals & Nature", emoji: "🐴", keywords: ["horse", "farm", "animal"] },
  {
    label: "unicorn",
    type: "Animals & Nature",
    emoji: "🦄",
    keywords: ["unicorn", "mythical", "animal"],
  },

  { label: "bee", type: "Animals & Nature", emoji: "🐝", keywords: ["bee", "insect", "animal"] },
  { label: "worm", type: "Animals & Nature", emoji: "🪱", keywords: ["worm", "insect", "animal"] },
  { label: "bug", type: "Animals & Nature", emoji: "🐛", keywords: ["bug", "insect", "animal"] },
  {
    label: "butterfly",
    type: "Animals & Nature",
    emoji: "🦋",
    keywords: ["butterfly", "insect", "animal"],
  },
  {
    label: "snail",
    type: "Animals & Nature",
    emoji: "🐌",
    keywords: ["snail", "mollusk", "animal"],
  },
  { label: "shell", type: "Animals & Nature", emoji: "🐚", keywords: ["shell", "sea", "nature"] },
  {
    label: "mosquito",
    type: "Animals & Nature",
    emoji: "🦟",
    keywords: ["mosquito", "insect", "animal"],
  },
  {
    label: "lady beetle",
    type: "Animals & Nature",
    emoji: "🐞",
    keywords: ["ladybug", "insect", "animal"],
  },
  { label: "ant", type: "Animals & Nature", emoji: "🐜", keywords: ["ant", "insect", "animal"] },

  {
    label: "turtle",
    type: "Animals & Nature",
    emoji: "🐢",
    keywords: ["turtle", "reptile", "animal"],
  },
  {
    label: "snake",
    type: "Animals & Nature",
    emoji: "🐍",
    keywords: ["snake", "reptile", "animal"],
  },
  {
    label: "lizard",
    type: "Animals & Nature",
    emoji: "🦎",
    keywords: ["lizard", "reptile", "animal"],
  },
  {
    label: "dragon",
    type: "Animals & Nature",
    emoji: "🐉",
    keywords: ["dragon", "mythical", "animal"],
  },

  {
    label: "cactus",
    type: "Animals & Nature",
    emoji: "🌵",
    keywords: ["cactus", "plant", "nature"],
  },
  {
    label: "evergreen tree",
    type: "Animals & Nature",
    emoji: "🌲",
    keywords: ["tree", "forest", "nature"],
  },
  { label: "deciduous tree", type: "Animals & Nature", emoji: "🌳", keywords: ["tree", "nature"] },
  {
    label: "palm tree",
    type: "Animals & Nature",
    emoji: "🌴",
    keywords: ["palm", "tree", "nature"],
  },
  {
    label: "seedling",
    type: "Animals & Nature",
    emoji: "🌱",
    keywords: ["plant", "growth", "nature"],
  },
  { label: "herb", type: "Animals & Nature", emoji: "🌿", keywords: ["herb", "plant", "nature"] },
  {
    label: "four leaf clover",
    type: "Animals & Nature",
    emoji: "🍀",
    keywords: ["clover", "luck", "nature"],
  },
  {
    label: "mushroom",
    type: "Animals & Nature",
    emoji: "🍄",
    keywords: ["mushroom", "fungus", "nature"],
  },

  { label: "sun", type: "Animals & Nature", emoji: "🌞", keywords: ["sun", "day", "nature"] },
  { label: "moon", type: "Animals & Nature", emoji: "🌙", keywords: ["moon", "night", "nature"] },
  {
    label: "stars",
    type: "Animals & Nature",
    emoji: "✨",
    keywords: ["stars", "sparkle", "nature"],
  },
  { label: "fire", type: "Animals & Nature", emoji: "🔥", keywords: ["fire", "heat", "nature"] },
  {
    label: "rainbow",
    type: "Animals & Nature",
    emoji: "🌈",
    keywords: ["rainbow", "weather", "nature"],
  },
  { label: "cloud", type: "Animals & Nature", emoji: "☁", keywords: ["cloud", "sky", "nature"] },
  { label: "rain", type: "Animals & Nature", emoji: "🌧", keywords: ["rain", "weather", "nature"] },
  { label: "snow", type: "Animals & Nature", emoji: "❄", keywords: ["snow", "cold", "nature"] },
  { label: "wind", type: "Animals & Nature", emoji: "💨", keywords: ["wind", "air", "nature"] },
  {
    label: "water wave",
    type: "Animals & Nature",
    emoji: "🌊",
    keywords: ["water", "ocean", "nature"],
  },
  {
    label: "droplet",
    type: "Animals & Nature",
    emoji: "💧",
    keywords: ["water", "drop", "nature"],
  },
  {
    label: "umbrella rain",
    type: "Animals & Nature",
    emoji: "☔",
    keywords: ["rain", "umbrella", "weather"],
  },

  //   flags
  {
    label: "CN",
    type: "Flags",
    emoji: "🇨🇳",
    keywords: ["China", "flag", "country"],
  },
  {
    label: "IN",
    type: "Flags",
    emoji: "🇮🇳",
    keywords: ["India", "flag", "country"],
  },
  {
    label: "JP",
    type: "Flags",
    emoji: "🇯🇵",
    keywords: ["Japan", "flag", "country"],
  },
  {
    label: "KR",
    type: "Flags",
    emoji: "🇰🇷",
    keywords: ["South Korea", "flag", "country", "ROK"],
  },
  {
    label: "GB",
    type: "Flags",
    emoji: "🇬🇧",
    keywords: ["United Kingdom", "flag", "country", "UK", "Britain"],
  },
  {
    label: "US",
    type: "Flags",
    emoji: "🇺🇸",
    keywords: ["United States", "flag", "country", "USA"],
  },
  {
    label: "AF",
    type: "Flags",
    emoji: "🇦🇫",
    keywords: ["Afghanistan", "flag", "country"],
  },
  {
    label: "AL",
    type: "Flags",
    emoji: "🇦🇱",
    keywords: ["Albania", "flag", "country"],
  },
  {
    label: "DZ",
    type: "Flags",
    emoji: "🇩🇿",
    keywords: ["Algeria", "flag", "country"],
  },
  {
    label: "AR",
    type: "Flags",
    emoji: "🇦🇷",
    keywords: ["Argentina", "flag", "country"],
  },
  {
    label: "AU",
    type: "Flags",
    emoji: "🇦🇺",
    keywords: ["Australia", "flag", "country"],
  },
  {
    label: "BR",
    type: "Flags",
    emoji: "🇧🇷",
    keywords: ["Brazil", "flag", "country"],
  },
  {
    label: "CA",
    type: "Flags",
    emoji: "🇨🇦",
    keywords: ["Canada", "flag", "country"],
  },

  {
    label: "FR",
    type: "Flags",
    emoji: "🇫🇷",
    keywords: ["France", "flag", "country"],
  },
  {
    label: "DE",
    type: "Flags",
    emoji: "🇩🇪",
    keywords: ["Germany", "flag", "country"],
  },
  {
    label: "IQ",
    type: "Flags",
    emoji: "🇮🇶",
    keywords: ["Iraq", "flag", "country"],
  },
  {
    label: "IR",
    type: "Flags",
    emoji: "🇮🇷",
    keywords: ["Iran", "flag", "country"],
  },
  {
    label: "IT",
    type: "Flags",
    emoji: "🇮🇹",
    keywords: ["Italy", "flag", "country"],
  },
  {
    label: "MX",
    type: "Flags",
    emoji: "🇲🇽",
    keywords: ["Mexico", "flag", "country"],
  },
  {
    label: "NG",
    type: "Flags",
    emoji: "🇳🇬",
    keywords: ["Nigeria", "flag", "country"],
  },
  {
    label: "PK",
    type: "Flags",
    emoji: "🇵🇰",
    keywords: ["Pakistan", "flag", "country"],
  },
  {
    label: "RU",
    type: "Flags",
    emoji: "🇷🇺",
    keywords: ["Russia", "flag", "country"],
  },
  {
    label: "SA",
    type: "Flags",
    emoji: "🇸🇦",
    keywords: ["Saudi Arabia", "flag", "country"],
  },
  {
    label: "ZA",
    type: "Flags",
    emoji: "🇿🇦",
    keywords: ["South Africa", "flag", "country"],
  },
  {
    label: "ES",
    type: "Flags",
    emoji: "🇪🇸",
    keywords: ["Spain", "flag", "country"],
  },
  {
    label: "TR",
    type: "Flags",
    emoji: "🇹🇷",
    keywords: ["Turkey", "flag", "country"],
  },
  {
    label: "BD",
    type: "Flags",
    emoji: "🇧🇩",
    keywords: ["Bangladesh", "flag", "country"],
  },
  {
    label: "BE",
    type: "Flags",
    emoji: "🇧🇪",
    keywords: ["Belgium", "flag", "country"],
  },
  {
    label: "CO",
    type: "Flags",
    emoji: "🇨🇴",
    keywords: ["Colombia", "flag", "country"],
  },
  {
    label: "EG",
    type: "Flags",
    emoji: "🇪🇬",
    keywords: ["Egypt", "flag", "country"],
  },
  {
    label: "ET",
    type: "Flags",
    emoji: "🇪🇹",
    keywords: ["Ethiopia", "flag", "country"],
  },
  {
    label: "GR",
    type: "Flags",
    emoji: "🇬🇷",
    keywords: ["Greece", "flag", "country"],
  },
  {
    label: "ID",
    type: "Flags",
    emoji: "🇮🇩",
    keywords: ["Indonesia", "flag", "country"],
  },
  {
    label: "IE",
    type: "Flags",
    emoji: "🇮🇪",
    keywords: ["Ireland", "flag", "country"],
  },
  {
    label: "IL",
    type: "Flags",
    emoji: "🇮🇱",
    keywords: ["Israel", "flag", "country"],
  },
  {
    label: "KE",
    type: "Flags",
    emoji: "🇰🇪",
    keywords: ["Kenya", "flag", "country"],
  },
  {
    label: "MY",
    type: "Flags",
    emoji: "🇲🇾",
    keywords: ["Malaysia", "flag", "country"],
  },
  {
    label: "NL",
    type: "Flags",
    emoji: "🇳🇱",
    keywords: ["Netherlands", "flag", "country"],
  },
  {
    label: "NZ",
    type: "Flags",
    emoji: "🇳🇿",
    keywords: ["New Zealand", "flag", "country"],
  },
  {
    label: "PE",
    type: "Flags",
    emoji: "🇵🇪",
    keywords: ["Peru", "flag", "country"],
  },
  {
    label: "PH",
    type: "Flags",
    emoji: "🇵🇭",
    keywords: ["Philippines", "flag", "country"],
  },
  {
    label: "PL",
    type: "Flags",
    emoji: "🇵🇱",
    keywords: ["Poland", "flag", "country"],
  },
  {
    label: "PT",
    type: "Flags",
    emoji: "🇵🇹",
    keywords: ["Portugal", "flag", "country"],
  },
  {
    label: "SE",
    type: "Flags",
    emoji: "🇸🇪",
    keywords: ["Sweden", "flag", "country"],
  },
  {
    label: "TH",
    type: "Flags",
    emoji: "🇹🇭",
    keywords: ["Thailand", "flag", "country"],
  },
  {
    label: "UA",
    type: "Flags",
    emoji: "🇺🇦",
    keywords: ["Ukraine", "flag", "country"],
  },
  {
    label: "VN",
    type: "Flags",
    emoji: "🇻🇳",
    keywords: ["Vietnam", "flag", "country"],
  },
  {
    label: "AT",
    type: "Flags",
    emoji: "🇦🇹",
    keywords: ["Austria", "flag", "country"],
  },
  {
    label: "CL",
    type: "Flags",
    emoji: "🇨🇱",
    keywords: ["Chile", "flag", "country"],
  },
  {
    label: "CU",
    type: "Flags",
    emoji: "🇨🇺",
    keywords: ["Cuba", "flag", "country"],
  },
  {
    label: "CZ",
    type: "Flags",
    emoji: "🇨🇿",
    keywords: ["Czechia", "flag", "country", "czech_republic"],
  },
  {
    label: "DK",
    type: "Flags",
    emoji: "🇩🇰",
    keywords: ["Denmark", "flag", "country"],
  },
  {
    label: "FI",
    type: "Flags",
    emoji: "🇫🇮",
    keywords: ["Finland", "flag", "country"],
  },
  {
    label: "HU",
    type: "Flags",
    emoji: "🇭🇺",
    keywords: ["Hungary", "flag", "country"],
  },
  {
    label: "NO",
    type: "Flags",
    emoji: "🇳🇴",
    keywords: ["Norway", "flag", "country"],
  },
  {
    label: "RO",
    type: "Flags",
    emoji: "🇷🇴",
    keywords: ["Romania", "flag", "country"],
  },
  {
    label: "SG",
    type: "Flags",
    emoji: "🇸🇬",
    keywords: ["Singapore", "flag", "country"],
  },
  {
    label: "SK",
    type: "Flags",
    emoji: "🇸🇰",
    keywords: ["Slovakia", "flag", "country"],
  },
  {
    label: "CH",
    type: "Flags",
    emoji: "🇨🇭",
    keywords: ["Switzerland", "flag", "country"],
  },
  {
    label: "UY",
    type: "Flags",
    emoji: "🇺🇾",
    keywords: ["Uruguay", "flag", "country"],
  },
  {
    label: "VE",
    type: "Flags",
    emoji: "🇻🇪",
    keywords: ["Venezuela", "flag", "country"],
  },

  //  food
  {
    label: "green apple",
    type: "Food",
    emoji: "🍏",
    keywords: ["apple", "green", "fruit", "fresh"],
  },
  { label: "red apple", type: "Food", emoji: "🍎", keywords: ["apple", "red", "fruit"] },
  { label: "pear", type: "Food", emoji: "🍐", keywords: ["pear", "fruit", "fresh"] },
  { label: "orange", type: "Food", emoji: "🍊", keywords: ["orange", "citrus", "fruit"] },
  { label: "lemon", type: "Food", emoji: "🍋", keywords: ["lemon", "citrus", "sour"] },
  { label: "banana", type: "Food", emoji: "🍌", keywords: ["banana", "fruit", "yellow"] },
  { label: "water melon", type: "Food", emoji: "🍉", keywords: ["watermelon", "fruit", "summer"] },
  { label: "grapes", type: "Food", emoji: "🍇", keywords: ["grapes", "fruit", "wine"] },
  { label: "straw berry", type: "Food", emoji: "🍓", keywords: ["strawberry", "berry", "fruit"] },
  { label: "blue berries", type: "Food", emoji: "🫐", keywords: ["blueberry", "berry", "fruit"] },
  { label: "melon", type: "Food", emoji: "🍈", keywords: ["melon", "fruit", "fresh"] },
  { label: "cherries", type: "Food", emoji: "🍒", keywords: ["cherry", "fruit", "sweet"] },
  { label: "peach", type: "Food", emoji: "🍑", keywords: ["peach", "fruit", "sweet"] },
  { label: "mango", type: "Food", emoji: "🥭", keywords: ["mango", "fruit", "tropical"] },
  { label: "pine apple", type: "Food", emoji: "🍍", keywords: ["pineapple", "fruit", "tropical"] },
  { label: "coconut", type: "Food", emoji: "🥥", keywords: ["coconut", "fruit", "tropical"] },
  { label: "kiwi", type: "Food", emoji: "🥝", keywords: ["kiwi", "fruit", "green"] },
  { label: "avoc ado", type: "Food", emoji: "🥑", keywords: ["avocado", "fruit", "healthy"] },
  { label: "tomato", type: "Food", emoji: "🍅", keywords: ["tomato", "vegetable", "salad"] },
  {
    label: "egg plant",
    type: "Food",
    emoji: "🍆",
    keywords: ["eggplant", "vegetable", "aubergine"],
  },
  { label: "broc coli", type: "Food", emoji: "🥦", keywords: ["broccoli", "vegetable", "green"] },
  {
    label: "leafy greens",
    type: "Food",
    emoji: "🥬",
    keywords: ["greens", "vegetable", "healthy"],
  },
  { label: "cucum ber", type: "Food", emoji: "🥒", keywords: ["cucumber", "vegetable", "fresh"] },
  { label: "carrot", type: "Food", emoji: "🥕", keywords: ["carrot", "vegetable", "orange"] },
  { label: "olive", type: "Food", emoji: "🫒", keywords: ["olive", "oil", "mediterranean"] },
  { label: "garlic", type: "Food", emoji: "🧄", keywords: ["garlic", "spice", "flavor"] },
  { label: "onion", type: "Food", emoji: "🧅", keywords: ["onion", "vegetable", "flavor"] },
  { label: "corn", type: "Food", emoji: "🌽", keywords: ["corn", "maize", "vegetable"] },
  { label: "chili pepper", type: "Food", emoji: "🌶", keywords: ["chili", "spicy", "pepper"] },
  {
    label: "bell pepper",
    type: "Food",
    emoji: "🫑",
    keywords: ["pepper", "capsicum", "vegetable"],
  },
  { label: "potato", type: "Food", emoji: "🥔", keywords: ["potato", "vegetable", "starch"] },
  { label: "sweet potato", type: "Food", emoji: "🍠", keywords: ["sweet potato", "yam", "root"] },

  { label: "bread", type: "Food", emoji: "🍞", keywords: ["bread", "bakery", "loaf"] },
  { label: "french", type: "Food", emoji: "🥖", keywords: ["baguette", "bread", "french"] },
  {
    label: "french",
    type: "Food",
    emoji: "🥐",
    keywords: ["quaso:3", "bread", "french", "Croissant"],
  },
  { label: "pretzel", type: "Food", emoji: "🥨", keywords: ["pretzel", "snack", "bread"] },
  { label: "cheese", type: "Food", emoji: "🧀", keywords: ["cheese", "dairy", "milk"] },
  { label: "egg", type: "Food", emoji: "🥚", keywords: ["egg", "protein", "breakfast"] },
  { label: "bacon", type: "Food", emoji: "🥓", keywords: ["bacon", "meat", "breakfast"] },
  { label: "meat", type: "Food", emoji: "🥩", keywords: ["meat", "steak", "protein"] },
  { label: "pizza", type: "Food", emoji: "🍕", keywords: ["pizza", "fast food", "cheese"] },
  { label: "burger", type: "Food", emoji: "🍔", keywords: ["burger", "fast food", "beef"] },
  { label: "fries", type: "Food", emoji: "🍟", keywords: ["fries", "potato", "fast food"] },
  { label: "taco", type: "Food", emoji: "🌮", keywords: ["taco", "mexican", "street food"] },
  { label: "burrito", type: "Food", emoji: "🌯", keywords: ["burrito", "mexican", "wrap"] },
  { label: "salad", type: "Food", emoji: "🥗", keywords: ["salad", "healthy", "greens"] },
  { label: "soup", type: "Food", emoji: "🍲", keywords: ["soup", "hot", "comfort"] },

  { label: "cake", type: "Food", emoji: "🍰", keywords: ["cake", "dessert", "sweet"] },
  {
    label: "birthday cake",
    type: "Food",
    emoji: "🎂",
    keywords: ["birthday", "cake", "celebration"],
  },
  { label: "ice cream", type: "Food", emoji: "🍨", keywords: ["ice cream", "dessert", "cold"] },
  { label: "cookie", type: "Food", emoji: "🍪", keywords: ["cookie", "dessert", "biscuit"] },
  { label: "chocolate", type: "Food", emoji: "🍫", keywords: ["chocolate", "sweet", "candy"] },
  { label: "popcorn", type: "Food", emoji: "🍿", keywords: ["popcorn", "snack", "movie"] },

  { label: "coffee", type: "Food", emoji: "☕", keywords: ["coffee", "drink", "caffeine"] },
  { label: "tea", type: "Food", emoji: "🍵", keywords: ["tea", "drink", "hot"] },
  { label: "juice", type: "Food", emoji: "🧃", keywords: ["juice", "drink", "fresh"] },
  { label: "beer", type: "Food", emoji: "🍺", keywords: ["beer", "alcohol", "drink"] },
  { label: "wine", type: "Food", emoji: "🍷", keywords: ["wine", "alcohol", "drink"] },

  { label: "spoon", type: "Food", emoji: "🥄", keywords: ["spoon", "utensil", "cutlery"] },
  { label: "fork and knife", type: "Food", emoji: "🍴", keywords: ["cutlery", "fork", "knife"] },
  { label: "plate", type: "Food", emoji: "🍽", keywords: ["plate", "meal", "dining"] },
  { label: "salt", type: "Food", emoji: "🧂", keywords: ["salt", "seasoning", "spice"] },
  //   travel
  { label: "car", type: "Travel & Places", emoji: "🚗", keywords: ["car", "drive", "vehicle"] },
  { label: "taxi", type: "Travel & Places", emoji: "🚕", keywords: ["taxi", "cab", "transport"] },
  { label: "bus", type: "Travel & Places", emoji: "🚌", keywords: ["bus", "public transport"] },
  {
    label: "police car",
    type: "Travel & Places",
    emoji: "🚓",
    keywords: ["police", "law", "emergency"],
  },
  {
    label: "ambulance",
    type: "Travel & Places",
    emoji: "🚑",
    keywords: ["ambulance", "medical", "emergency"],
  },
  {
    label: "fire engine",
    type: "Travel & Places",
    emoji: "🚒",
    keywords: ["fire", "emergency", "truck"],
  },
  {
    label: "truck",
    type: "Travel & Places",
    emoji: "🚚",
    keywords: ["truck", "delivery", "transport"],
  },
  {
    label: "tractor",
    type: "Travel & Places",
    emoji: "🚜",
    keywords: ["tractor", "farm", "vehicle"],
  },

  {
    label: "wheelchair",
    type: "Travel & Places",
    emoji: "🦽",
    keywords: ["wheelchair", "accessibility"],
  },
  {
    label: "scooter",
    type: "Travel & Places",
    emoji: "🛴",
    keywords: ["scooter", "ride", "transport"],
  },
  {
    label: "bicycle",
    type: "Travel & Places",
    emoji: "🚲",
    keywords: ["bicycle", "bike", "cycling"],
  },
  {
    label: "motorbike",
    type: "Travel & Places",
    emoji: "🏍",
    keywords: ["motorbike", "bike", "ride"],
  },

  { label: "tram", type: "Travel & Places", emoji: "🚋", keywords: ["tram", "city", "rail"] },
  {
    label: "train",
    type: "Travel & Places",
    emoji: "🚆",
    keywords: ["train", "railway", "travel"],
  },
  {
    label: "metro",
    type: "Travel & Places",
    emoji: "🚇",
    keywords: ["metro", "subway", "underground"],
  },
  {
    label: "station",
    type: "Travel & Places",
    emoji: "🚉",
    keywords: ["station", "railway", "stop"],
  },

  {
    label: "helicopter",
    type: "Travel & Places",
    emoji: "🚁",
    keywords: ["helicopter", "air", "transport"],
  },
  {
    label: "airplane",
    type: "Travel & Places",
    emoji: "✈️",
    keywords: ["airplane", "flight", "travel"],
  },
  {
    label: "rocket",
    type: "Travel & Places",
    emoji: "🚀",
    keywords: ["rocket", "space", "launch"],
  },
  {
    label: "satellite",
    type: "Travel & Places",
    emoji: "🛰",
    keywords: ["satellite", "space", "orbit"],
  },

  { label: "canoe", type: "Travel & Places", emoji: "🛶", keywords: ["canoe", "boat", "water"] },
  {
    label: "sailboat",
    type: "Travel & Places",
    emoji: "⛵",
    keywords: ["sailboat", "sea", "travel"],
  },
  { label: "ship", type: "Travel & Places", emoji: "🚢", keywords: ["ship", "cruise", "sea"] },
  { label: "anchor", type: "Travel & Places", emoji: "⚓", keywords: ["anchor", "harbor", "sea"] },

  {
    label: "fuel station",
    type: "Travel & Places",
    emoji: "⛽",
    keywords: ["fuel", "gas", "petrol"],
  },
  { label: "map", type: "Travel & Places", emoji: "🗺", keywords: ["map", "navigation", "travel"] },

  {
    label: "statue",
    type: "Travel & Places",
    emoji: "🗽",
    keywords: ["statue", "landmark", "tourism"],
  },
  {
    label: "fountain",
    type: "Travel & Places",
    emoji: "⛲",
    keywords: ["fountain", "city", "landmark"],
  },
  { label: "tower", type: "Travel & Places", emoji: "🗼", keywords: ["tower", "city", "landmark"] },
  {
    label: "castle",
    type: "Travel & Places",
    emoji: "🏰",
    keywords: ["castle", "historic", "tourism"],
  },
  {
    label: "stadium",
    type: "Travel & Places",
    emoji: "🏟",
    keywords: ["stadium", "sports", "arena"],
  },
  {
    label: "ferris wheel",
    type: "Travel & Places",
    emoji: "🎡",
    keywords: ["ferris wheel", "fair", "fun"],
  },

  { label: "beach", type: "Travel & Places", emoji: "🏖", keywords: ["beach", "sea", "vacation"] },
  {
    label: "island",
    type: "Travel & Places",
    emoji: "🏝",
    keywords: ["island", "tropical", "travel"],
  },
  {
    label: "mountains",
    type: "Travel & Places",
    emoji: "⛰️",
    keywords: ["mountains", "hiking", "nature"],
  },
  {
    label: "volcano",
    type: "Travel & Places",
    emoji: "🌋",
    keywords: ["volcano", "nature", "lava"],
  },
  { label: "desert", type: "Travel & Places", emoji: "🏜", keywords: ["desert", "sand", "nature"] },
  {
    label: "camping",
    type: "Travel & Places",
    emoji: "🏕",
    keywords: ["camping", "outdoor", "tent"],
  },

  { label: "house", type: "Travel & Places", emoji: "🏠", keywords: ["house", "home", "building"] },
  { label: "hotel", type: "Travel & Places", emoji: "🏨", keywords: ["hotel", "stay", "travel"] },
  {
    label: "hospital",
    type: "Travel & Places",
    emoji: "🏥",
    keywords: ["hospital", "medical", "health"],
  },
  {
    label: "bank",
    type: "Travel & Places",
    emoji: "🏦",
    keywords: ["bank", "finance", "building"],
  },
  {
    label: "school",
    type: "Travel & Places",
    emoji: "🏫",
    keywords: ["school", "education", "building"],
  },

  {
    label: "church",
    type: "Travel & Places",
    emoji: "⛪",
    keywords: ["church", "religion", "place"],
  },
  {
    label: "mosque",
    type: "Travel & Places",
    emoji: "🕌",
    keywords: ["mosque", "religion", "place"],
  },
  {
    label: "temple",
    type: "Travel & Places",
    emoji: "🛕",
    keywords: ["temple", "religion", "place"],
  },

  {
    label: "sunrise",
    type: "Travel & Places",
    emoji: "🌅",
    keywords: ["sunrise", "morning", "sky"],
  },
  {
    label: "sunset",
    type: "Travel & Places",
    emoji: "🌇",
    keywords: ["sunset", "evening", "city"],
  },
  {
    label: "night city",
    type: "Travel & Places",
    emoji: "🌃",
    keywords: ["night", "city", "lights"],
  },
  { label: "stars", type: "Travel & Places", emoji: "🌌", keywords: ["stars", "night", "sky"] },
  {
    label: "bridge",
    type: "Travel & Places",
    emoji: "🌉",
    keywords: ["bridge", "city", "landmark"],
  },
  // Activites
  { label: "football", type: "Activites", emoji: "⚽", keywords: ["football", "soccer", "sport"] },
  {
    label: "basketball",
    type: "Activites",
    emoji: "🏀",
    keywords: ["basketball", "sport", "hoop"],
  },
  {
    label: "american football",
    type: "Activites",
    emoji: "🏈",
    keywords: ["american football", "nfl", "sport"],
  },
  { label: "baseball", type: "Activites", emoji: "⚾", keywords: ["baseball", "sport", "bat"] },
  { label: "softball", type: "Activites", emoji: "🥎", keywords: ["softball", "sport", "ball"] },
  { label: "tennis", type: "Activites", emoji: "🎾", keywords: ["tennis", "sport", "racket"] },
  {
    label: "volleyball",
    type: "Activites",
    emoji: "🏐",
    keywords: ["volleyball", "sport", "team"],
  },
  { label: "rugby", type: "Activites", emoji: "🏉", keywords: ["rugby", "sport", "contact"] },
  {
    label: "flying disc",
    type: "Activites",
    emoji: "🥏",
    keywords: ["frisbee", "disc", "outdoor"],
  },
  {
    label: "billiards",
    type: "Activites",
    emoji: "🎱",
    keywords: ["billiards", "pool", "snooker"],
  },

  {
    label: "table tennis",
    type: "Activites",
    emoji: "🏓",
    keywords: ["ping pong", "table tennis", "sport"],
  },
  {
    label: "badminton",
    type: "Activites",
    emoji: "🏸",
    keywords: ["badminton", "shuttle", "racket"],
  },
  { label: "ice hockey", type: "Activites", emoji: "🏒", keywords: ["ice hockey", "sport", "ice"] },
  { label: "field hockey", type: "Activites", emoji: "🏑", keywords: ["field hockey", "sport"] },
  { label: "lacrosse", type: "Activites", emoji: "🥍", keywords: ["lacrosse", "sport", "stick"] },
  { label: "cricket", type: "Activites", emoji: "🏏", keywords: ["cricket", "sport", "bat"] },
  { label: "golf", type: "Activites", emoji: "⛳", keywords: ["golf", "sport", "hole"] },
  { label: "archery", type: "Activites", emoji: "🏹", keywords: ["archery", "bow", "target"] },
  { label: "fishing", type: "Activites", emoji: "🎣", keywords: ["fishing", "outdoor", "hobby"] },
  { label: "diving", type: "Activites", emoji: "🤿", keywords: ["diving", "snorkel", "water"] },

  { label: "boxing", type: "Activites", emoji: "🥊", keywords: ["boxing", "fight", "sport"] },
  {
    label: "martial arts",
    type: "Activites",
    emoji: "🥋",
    keywords: ["martial arts", "karate", "judo"],
  },
  {
    label: "skateboarding",
    type: "Activites",
    emoji: "🛹",
    keywords: ["skateboard", "street", "sport"],
  },
  {
    label: "roller skating",
    type: "Activites",
    emoji: "🛼",
    keywords: ["roller skating", "skates"],
  },
  { label: "ice skating", type: "Activites", emoji: "⛸️", keywords: ["ice skating", "winter"] },
  { label: "curling", type: "Activites", emoji: "🥌", keywords: ["curling", "ice", "sport"] },
  { label: "sledding", type: "Activites", emoji: "🛷", keywords: ["sledding", "snow", "winter"] },
  { label: "skiing", type: "Activites", emoji: "🎿", keywords: ["skiing", "snow", "winter"] },
  {
    label: "snowboarding",
    type: "Activites",
    emoji: "🏂",
    keywords: ["snowboard", "snow", "sport"],
  },
  {
    label: "parachuting",
    type: "Activites",
    emoji: "🪂",
    keywords: ["parachute", "skydiving", "air"],
  },

  {
    label: "weight lifting",
    type: "Activites",
    emoji: "🏋‍♂️",
    keywords: ["gym", "weights", "strength"],
  },
  { label: "gymnastics", type: "Activites", emoji: "🤸‍♀️", keywords: ["gymnastics", "flexibility"] },
  {
    label: "basketball dribbling",
    type: "Activites",
    emoji: "⛹️‍♂️",
    keywords: ["basketball", "dribble"],
  },
  { label: "handball", type: "Activites", emoji: "🤾‍♂️", keywords: ["handball", "throw", "sport"] },
  { label: "golf swing", type: "Activites", emoji: "🏌‍♂️", keywords: ["golf", "swing"] },
  { label: "yoga", type: "Activites", emoji: "🧘‍♀️", keywords: ["yoga", "meditation", "calm"] },
  { label: "surfing", type: "Activites", emoji: "🏄‍♂️", keywords: ["surfing", "waves", "sea"] },
  { label: "swimming", type: "Activites", emoji: "🏊‍♂️", keywords: ["swimming", "water", "sport"] },
  { label: "rowing", type: "Activites", emoji: "🚣‍♂️", keywords: ["rowing", "boat", "water"] },
  {
    label: "horse riding",
    type: "Activites",
    emoji: "🏇",
    keywords: ["horse riding", "equestrian"],
  },

  {
    label: "climbing",
    type: "Activites",
    emoji: "🧗‍♂️",
    keywords: ["climbing", "mountain", "sport"],
  },
  { label: "cycling", type: "Activites", emoji: "🚴", keywords: ["cycling", "bike", "ride"] },
  {
    label: "mountain biking",
    type: "Activites",
    emoji: "🚵‍♀️",
    keywords: ["mountain bike", "trail"],
  },

  { label: "medal", type: "Activites", emoji: "🏅", keywords: ["medal", "achievement", "sport"] },
  { label: "trophy", type: "Activites", emoji: "🏆", keywords: ["trophy", "winner", "award"] },

  { label: "circus", type: "Activites", emoji: "🎪", keywords: ["circus", "show", "fun"] },
  { label: "juggling", type: "Activites", emoji: "🤹‍♂️", keywords: ["juggling", "skill", "circus"] },
  { label: "theater", type: "Activites", emoji: "🎭", keywords: ["theater", "drama", "acting"] },
  { label: "ballet", type: "Activites", emoji: "🩰", keywords: ["ballet", "dance", "art"] },
  { label: "painting", type: "Activites", emoji: "🎨", keywords: ["painting", "art", "creative"] },
  { label: "filming", type: "Activites", emoji: "🎬", keywords: ["film", "movie", "cinema"] },

  { label: "music", type: "Activites", emoji: "🎵", keywords: ["music", "sound", "notes"] },
  { label: "piano", type: "Activites", emoji: "🎹", keywords: ["piano", "music", "instrument"] },
  { label: "drums", type: "Activites", emoji: "🥁", keywords: ["drums", "music", "beat"] },
  { label: "guitar", type: "Activites", emoji: "🎸", keywords: ["guitar", "music", "instrument"] },
  { label: "violin", type: "Activites", emoji: "🎻", keywords: ["violin", "music", "strings"] },

  { label: "dice game", type: "Activites", emoji: "🎲", keywords: ["dice", "game", "luck"] },
  { label: "chess", type: "Activites", emoji: "♟️", keywords: ["chess", "board game", "strategy"] },
  { label: "dart", type: "Activites", emoji: "🎯", keywords: ["dart", "target", "aim"] },
  { label: "bowling", type: "Activites", emoji: "🎳", keywords: ["bowling", "pins", "game"] },
  { label: "video game", type: "Activites", emoji: "🎮", keywords: ["gaming", "console", "play"] },
  { label: "puzzle", type: "Activites", emoji: "🧩", keywords: ["puzzle", "brain", "logic"] },
  { label: "cards", type: "Activites", emoji: "🃏", keywords: ["cards", "game", "deck"] },
  // objects
  { label: "watch", type: "Objects", emoji: "⌚", keywords: ["watch", "time", "wrist"] },
  {
    label: "mobile phone",
    type: "Objects",
    emoji: "📱",
    keywords: ["mobile", "phone", "cell", "iphone"],
  },
  {
    label: "laptop",
    type: "Objects",
    emoji: "💻",
    keywords: ["laptop", "computer", "pc", "macbook"],
  },
  { label: "keyboard", type: "Objects", emoji: "⌨️", keywords: ["keyboard", "typing", "input"] },
  {
    label: "desktop computer",
    type: "Objects",
    emoji: "🖥",
    keywords: ["computer", "desktop", "monitor", "screen"],
  },
  { label: "printer", type: "Objects", emoji: "🖨", keywords: ["printer", "paper", "office"] },
  {
    label: "computer mouse",
    type: "Objects",
    emoji: "🖱",
    keywords: ["mouse", "click", "computer"],
  },
  {
    label: "joystick",
    type: "Objects",
    emoji: "🕹",
    keywords: ["joystick", "game", "controller", "retro"],
  },
  { label: "camera", type: "Objects", emoji: "📷", keywords: ["camera", "photo", "photography"] },
  {
    label: "video camera",
    type: "Objects",
    emoji: "📹",
    keywords: ["video", "camera", "movie", "record"],
  },
  {
    label: "telephone",
    type: "Objects",
    emoji: "☎",
    keywords: ["telephone", "phone", "landline", "call"],
  },
  {
    label: "television",
    type: "Objects",
    emoji: "📺",
    keywords: ["television", "tv", "screen", "show"],
  },
  {
    label: "radio",
    type: "Objects",
    emoji: "📻",
    keywords: ["radio", "music", "broadcast", "audio"],
  },
  {
    label: "battery",
    type: "Objects",
    emoji: "🔋",
    keywords: ["battery", "power", "energy", "charge"],
  },
  {
    label: "electric plug",
    type: "Objects",
    emoji: "🔌",
    keywords: ["plug", "electric", "power", "cable"],
  },
  {
    label: "light bulb",
    type: "Objects",
    emoji: "💡",
    keywords: ["light", "bulb", "idea", "bright"],
  },
  {
    label: "flashlight",
    type: "Objects",
    emoji: "🔦",
    keywords: ["flashlight", "torch", "light", "dark"],
  },
  {
    label: "money bag",
    type: "Objects",
    emoji: "💰",
    keywords: ["money", "bag", "cash", "wealth", "gold"],
  },
  {
    label: "credit card",
    type: "Objects",
    emoji: "💳",
    keywords: ["credit", "card", "pay", "bank", "money"],
  },
  { label: "hammer", type: "Objects", emoji: "🔨", keywords: ["hammer", "tool", "build", "fix"] },
  {
    label: "wrench",
    type: "Objects",
    emoji: "🔧",
    keywords: ["wrench", "tool", "fix", "repair", "spanner"],
  },
  {
    label: "gear",
    type: "Objects",
    emoji: "⚙️",
    keywords: ["gear", "cog", "machine", "settings", "process"],
  },
  {
    label: "shield",
    type: "Objects",
    emoji: "🛡",
    keywords: ["shield", "protection", "defense", "security"],
  },
  {
    label: "crystal ball",
    type: "Objects",
    emoji: "🔮",
    keywords: ["crystal", "ball", "magic", "fortune", "future"],
  },
  {
    label: "microscope",
    type: "Objects",
    emoji: "🔬",
    keywords: ["microscope", "science", "lab", "study"],
  },
  {
    label: "telescope",
    type: "Objects",
    emoji: "🔭",
    keywords: ["telescope", "stars", "space", "astronomy"],
  },
  { label: "pill", type: "Objects", emoji: "💊", keywords: ["pill", "medicine", "drug", "health"] },
  {
    label: "syringe",
    type: "Objects",
    emoji: "💉",
    keywords: ["syringe", "needle", "vaccine", "injection", "doctor"],
  },
  {
    label: "toilet",
    type: "Objects",
    emoji: "🚽",
    keywords: ["toilet", "bathroom", "restroom", "wc"],
  },
  {
    label: "key",
    type: "Objects",
    emoji: "🔑",
    keywords: ["key", "lock", "access", "door", "password"],
  },
  {
    label: "shopping cart",
    type: "Objects",
    emoji: "🛒",
    keywords: ["cart", "shopping", "buy", "store"],
  },
  {
    label: "gift",
    type: "Objects",
    emoji: "🎁",
    keywords: ["gift", "present", "birthday", "box", "surprise"],
  },
  {
    label: "package",
    type: "Objects",
    emoji: "📦",
    keywords: ["package", "box", "delivery", "shipping", "mail"],
  },
  {
    label: "books",
    type: "Objects",
    emoji: "📚",
    keywords: ["books", "library", "reading", "study", "education"],
  },
  {
    label: "magnifying glass",
    type: "Objects",
    emoji: "🔍",
    keywords: ["search", "find", "zoom", "detective", "glass"],
  },
  {
    label: "locked",
    type: "Objects",
    emoji: "🔒",
    keywords: ["locked", "secure", "privacy", "closed"],
  },
  {
    label: "pager",
    type: "Objects",
    emoji: "📟",
    keywords: ["pager", "beeper", "communication", "old"],
  },
  {
    label: "fax machine",
    type: "Objects",
    emoji: "📠",
    keywords: ["fax", "machine", "office", "communication"],
  },
  {
    label: "compass",
    type: "Objects",
    emoji: "🧭",
    keywords: ["compass", "direction", "navigation", "map"],
  },
  {
    label: "stopwatch",
    type: "Objects",
    emoji: "⏱️",
    keywords: ["stopwatch", "time", "timer", "race"],
  },
  {
    label: "alarm clock",
    type: "Objects",
    emoji: "⏰",
    keywords: ["alarm", "clock", "time", "wake"],
  },
  {
    label: "hourglass",
    type: "Objects",
    emoji: "⌛",
    keywords: ["hourglass", "time", "sand", "waiting"],
  },
  {
    label: "satellite antenna",
    type: "Objects",
    emoji: "📡",
    keywords: ["satellite", "dish", "antenna", "signal"],
  },
  { label: "candle", type: "Objects", emoji: "🕯", keywords: ["candle", "light", "wax", "fire"] },
  {
    label: "fire extinguisher",
    type: "Objects",
    emoji: "🧯",
    keywords: ["fire", "extinguisher", "safety", "emergency"],
  },
  {
    label: "wastebasket",
    type: "Objects",
    emoji: "🗑",
    keywords: ["trash", "bin", "waste", "garbage", "delete"],
  },
  {
    label: "toolbox",
    type: "Objects",
    emoji: "🧰",
    keywords: ["toolbox", "tools", "fix", "repair"],
  },
  {
    label: "screwdriver",
    type: "Objects",
    emoji: "🪛",
    keywords: ["screwdriver", "tool", "screw", "fix"],
  },
  { label: "pick", type: "Objects", emoji: "⛏️", keywords: ["pick", "axe", "mining", "tool"] },
  {
    label: "chains",
    type: "Objects",
    emoji: "⛓️",
    keywords: ["chains", "metal", "link", "locked"],
  },
  {
    label: "magnet",
    type: "Objects",
    emoji: "🧲",
    keywords: ["magnet", "magnetic", "attract", "metal"],
  },
  { label: "bomb", type: "Objects", emoji: "💣", keywords: ["bomb", "explode", "danger", "error"] },
  { label: "axe", type: "Objects", emoji: "🪓", keywords: ["axe", "wood", "chop", "tool"] },
  {
    label: "kitchen knife",
    type: "Objects",
    emoji: "🔪",
    keywords: ["knife", "cut", "kitchen", "blade"],
  },
  {
    label: "test tube",
    type: "Objects",
    emoji: "🧪",
    keywords: ["test", "tube", "chemistry", "lab", "science"],
  },
  {
    label: "thermometer",
    type: "Objects",
    emoji: "🌡",
    keywords: ["thermometer", "temperature", "hot", "cold", "weather"],
  },
  { label: "broom", type: "Objects", emoji: "🧹", keywords: ["broom", "clean", "sweep", "dust"] },
  {
    label: "plunger",
    type: "Objects",
    emoji: "🪠",
    keywords: ["plunger", "toilet", "fix", "plumbing"],
  },
  { label: "soap", type: "Objects", emoji: "🧼", keywords: ["soap", "clean", "wash", "bubbles"] },
  { label: "razor", type: "Objects", emoji: "🪒", keywords: ["razor", "shave", "sharp"] },
  { label: "bed", type: "Objects", emoji: "🛏", keywords: ["bed", "sleep", "rest", "furniture"] },
  { label: "mirror", type: "Objects", emoji: "🪞", keywords: ["mirror", "reflection", "glass"] },
  {
    label: "balloon",
    type: "Objects",
    emoji: "🎈",
    keywords: ["balloon", "party", "celebration", "fly"],
  },
  { label: "e-mail", type: "Objects", emoji: "📧", keywords: ["email", "mail", "letter", "inbox"] },
  {
    label: "scroll",
    type: "Objects",
    emoji: "📜",
    keywords: ["scroll", "paper", "history", "document"],
  },
  {
    label: "chart increasing",
    type: "Objects",
    emoji: "📈",
    keywords: ["chart", "graph", "growth", "business", "data"],
  },
  {
    label: "clipboard",
    type: "Objects",
    emoji: "📋",
    keywords: ["clipboard", "list", "check", "tasks"],
  },
  {
    label: "folder",
    type: "Objects",
    emoji: "📁",
    keywords: ["folder", "file", "directory", "save"],
  },
  {
    label: "newspaper",
    type: "Objects",
    emoji: "📰",
    keywords: ["newspaper", "news", "press", "daily"],
  },
  {
    label: "paperclip",
    type: "Objects",
    emoji: "📎",
    keywords: ["paperclip", "attachment", "link", "office"],
  },
  {
    label: "ruler",
    type: "Objects",
    emoji: "📏",
    keywords: ["ruler", "measure", "length", "school"],
  },
  {
    label: "pencil",
    type: "Objects",
    emoji: "📝",
    keywords: ["pencil", "write", "note", "paper", "edit"],
  },
];
